import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { ExportTableRequest, TableSchema } from '../../shared/types'
import type { DbDriver } from './drivers/types'

const { appendFile, writeFile, showSaveDialog, getDriver, getTableSchema } = vi.hoisted(() => ({
  appendFile: vi.fn(async () => undefined),
  writeFile: vi.fn(async () => undefined),
  showSaveDialog: vi.fn(),
  getDriver: vi.fn(),
  getTableSchema: vi.fn()
}))

vi.mock('node:fs/promises', () => ({
  appendFile,
  writeFile
}))

vi.mock('electron', () => ({
  BrowserWindow: {
    getFocusedWindow: () => null,
    getAllWindows: () => []
  },
  dialog: {
    showSaveDialog
  }
}))

vi.mock('./db-service', () => ({
  dbService: {
    getDriver
  }
}))

vi.mock('./schema-service', () => ({
  schemaService: {
    getTableSchema
  }
}))

import { exportService } from './export-service'
import { mysqlDialect } from './drivers/mysql-dialect'

describe('ExportService', () => {
  beforeEach(() => {
    appendFile.mockClear()
    writeFile.mockClear()
    showSaveDialog.mockReset()
    getDriver.mockReset()
    getTableSchema.mockReset()
    showSaveDialog.mockResolvedValue({ canceled: false, filePath: '/tmp/users.sql' })
  })

  it('exports MySQL table data as PostgreSQL-compatible SQL', async () => {
    const { driver, streamRows } = createMySQLDriver({
      streamBatches: [
        [
          {
            id: 1,
            name: "O'Brien",
            active: 1,
            payload: Buffer.from('deadbeef', 'hex'),
            created_at: new Date('2024-01-02T03:04:05.000Z')
          }
        ]
      ]
    })

    getDriver.mockResolvedValue(driver)
    getTableSchema.mockResolvedValue(buildSchema())

    const result = await exportService.exportTable(
      createExportRequest({ sqlDialect: 'postgres' })
    )

    const output = getAppendedOutput()
    expect(result).toEqual({ canceled: false, filePath: '/tmp/users.sql', rowsExported: 1 })
    expect(streamRows).toHaveBeenCalledWith({
      database: 'shop',
      table: 'users',
      columns: ['id', 'name', 'active', 'payload', 'created_at'],
      primaryKey: ['id'],
      orderBy: undefined,
      where: undefined,
      batchSize: 1000
    })
    expect(output).toContain('CREATE SCHEMA IF NOT EXISTS "shop";')
    expect(output).toContain('CREATE TABLE "shop"."users"')
    expect(output).toContain('"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(output).toContain('"name" varchar(255) NOT NULL')
    expect(output).toContain('"active" smallint NOT NULL DEFAULT 1')
    expect(output).toContain('"payload" bytea')
    expect(output).toContain('INSERT INTO "shop"."users"')
    expect(output).toContain("'O''Brien'")
    expect(output).not.toContain('`')
    expect(output).not.toContain('AUTO_INCREMENT')
  })

  it('keeps source SQL dialect when no target dialect is selected', async () => {
    const { driver } = createMySQLDriver({
      streamBatches: [[{ id: 1, name: 'Ada', active: 1, payload: null, created_at: null }]]
    })

    getDriver.mockResolvedValue(driver)
    getTableSchema.mockResolvedValue(buildSchema())

    await exportService.exportTable(createExportRequest())

    const output = getAppendedOutput()
    expect(output).toContain('CREATE TABLE `users`')
    expect(output).toContain('INSERT INTO `shop`.`users`')
    expect(output).toContain('`name`')
  })

  it('rejects unsupported target SQL dialects before opening the save dialog', async () => {
    const { driver } = createPostgresDriver()

    getDriver.mockResolvedValue(driver)
    getTableSchema.mockResolvedValue(buildSchema())

    await expect(
      exportService.exportTable(createExportRequest({ connectionId: 'pg-conn', sqlDialect: 'mysql' }))
    ).rejects.toThrow('Exporting postgres tables as mysql SQL is not supported')

    expect(showSaveDialog).not.toHaveBeenCalled()
    expect(writeFile).not.toHaveBeenCalled()
    expect(appendFile).not.toHaveBeenCalled()
  })
})

function createMySQLDriver(options: { streamBatches: Record<string, unknown>[][] }): {
  driver: DbDriver
  streamRows: ReturnType<typeof vi.fn>
} {
  const streamRows = vi.fn(async function* () {
    for (const batch of options.streamBatches) {
      yield batch
    }
  })

  const driver = {
    engine: 'mysql',
    connectionId: 'mysql-conn',
    dialect: mysqlDialect,
    listDatabases: async () => [],
    listTables: async () => [],
    getTableSchema: async () => buildSchema(),
    queryRows: async () => ({ rows: [], total: 0 }),
    insertRow: async () => ({ insertId: 0, affectedRows: 0 }),
    updateRow: async () => ({ affectedRows: 0 }),
    deleteRows: async () => ({ affectedRows: 0 }),
    renameTable: async () => ({ table: '' }),
    copyTable: async () => ({ table: '' }),
    dropTable: async () => undefined,
    executeSQL: async () => undefined,
    streamRows,
    testConnection: async () => 'OK',
    close: async () => undefined
  } satisfies DbDriver

  return { driver, streamRows }
}

function createPostgresDriver(): { driver: DbDriver } {
  const streamRows = vi.fn(async function* () {
    yield []
  })

  const driver = {
    ...createMySQLDriver({ streamBatches: [] }).driver,
    engine: 'postgres',
    connectionId: 'pg-conn',
    streamRows
  } satisfies DbDriver

  return { driver }
}

function getAppendedOutput(): string {
  return appendFile.mock.calls.map((call) => String((call as unknown[])[1])).join('')
}

function buildSchema(): TableSchema {
  return {
    name: 'users',
    columns: [
      {
        name: 'id',
        type: 'int',
        nullable: false,
        defaultValue: null,
        isPrimaryKey: true,
        isAutoIncrement: true,
        comment: '',
        columnKey: 'PRI'
      },
      {
        name: 'name',
        type: 'varchar(255)',
        nullable: false,
        defaultValue: null,
        isPrimaryKey: false,
        isAutoIncrement: false,
        comment: '',
        columnKey: ''
      },
      {
        name: 'active',
        type: 'tinyint(1)',
        nullable: false,
        defaultValue: '1',
        isPrimaryKey: false,
        isAutoIncrement: false,
        comment: '',
        columnKey: ''
      },
      {
        name: 'payload',
        type: 'blob',
        nullable: true,
        defaultValue: null,
        isPrimaryKey: false,
        isAutoIncrement: false,
        comment: '',
        columnKey: ''
      },
      {
        name: 'created_at',
        type: 'datetime',
        nullable: true,
        defaultValue: 'CURRENT_TIMESTAMP',
        isPrimaryKey: false,
        isAutoIncrement: false,
        comment: '',
        columnKey: ''
      }
    ],
    indexes: [{ name: 'PRIMARY', columns: ['id'], unique: true, type: 'BTREE' }],
    primaryKey: ['id'],
    createSQL:
      'CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB'
  }
}

function createExportRequest(overrides?: Partial<ExportTableRequest>): ExportTableRequest {
  return {
    connectionId: 'mysql-conn',
    database: 'shop',
    table: 'users',
    format: 'sql',
    scope: 'all',
    includeCreateTable: true,
    includeData: true,
    ...overrides
  }
}